<a href="https://colab.research.google.com/github/roccipelaez/THC_Rocio_Pelaez/blob/main/octubre_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [2]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [3]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [4]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [5]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,:])

[ 6  7  8  9 10]


In [6]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,2])

[3]


In [7]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,3])

[4 9]


In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [9]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,2:6])

[[3 4 5]]


In [10]:
arr=np.array([41,42,43,44])
filter_arr=arr> 42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [11]:
arr=np.array([41,42,43,44])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]


In [12]:
x=np.array([1,2,3])
y=np.array([4,5,6])
suma=x+y
print(suma)

[5 7 9]


In [13]:
resta=x-y
print(resta)

[-3 -3 -3]


In [14]:
prod=x*y
print(f"La multiplicación es {prod}")

La multiplicación es [ 4 10 18]


In [15]:
div=x/y
print(f"la división es {div}")

la división es [0.25 0.4  0.5 ]


In [16]:
print(f"número pi= {np.pi}")

número pi= 3.141592653589793


In [17]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
coseno=np.cos(angulos)
print(f"Los senos{seno}")
print(f"De los ángulos {angulos}")
print(f"Los cosenos {coseno}")

Los senos[0.0000000e+00 1.0000000e+00 1.2246468e-16]
De los ángulos [0.         1.57079633 3.14159265]
Los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [18]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [19]:
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
matriz=x.reshape(4,2)
matriz

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
x.reshape(-1,1)
x.reshape(-1,1).shape

(8, 1)

In [22]:
x=np.linspace(0,1,3)
x

array([0. , 0.5, 1. ])

In [23]:
x=np.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [24]:
np.random.uniform(0,1,6)

array([0.56822862, 0.53605032, 0.45205311, 0.26104247, 0.72844005,
       0.68311087])

In [25]:
np.random.randint(0,10,size=1)

array([1])

In [26]:
int(input("Colocar un nunmero alertarorio del 1 al 10 "))
c=np.random.randint(0,11,size=1)
print("Es este tu numero?",c )
input("¿si o no?")


Colocar un nunmero alertarorio del 1 al 10 5
Es este tu numero? [2]
¿si o no?no


'no'